brand: _brand.yml

filters:
  - _extensions/gfm-callout.lua

format:
  typst:
    toc: true
    toc-depth: 2
    number-sections: false
    fontsize: 11pt
    tbl-colwidths: auto
    template: _extensions/typst-template.typ
    template-partials:
      - _extensions/typst-show.typ

  odt:
    toc: true

  epub:
    toc: true

  gfm:
    toc: false